### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by doraniccole**
adjusting items placement

### CODE REVIEW

**Review by RobertWRadford — CHANGES_REQUESTED** [review]
Merge conflict markers on lines 6 - 19

**Review by doraniccole — COMMENTED** [review]
super adjustment

**Review by doraniccole — COMMENTED** [review]
great

**Review by doraniccole — COMMENTED** [review]
consider managing merge conflict notices

**Comment by RobertWRadford** [comment]
Had conflicts

**Pull request closed without merging**
